services:
    mysql:
      restart: unless-stopped
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: flores_password_reservue
        MYSQL_DATABASE: flores_db_reservue
        MYSQL_USER: flores_user_reservue
        MYSQL_PASSWORD: flores_password_reservue
      ports:
      - "3306:3306"
      volumes:
      - mysql_data:/var/lib/mysql
      networks:
      - flores_reservue_network


    app:
     build:
      context: .
      dockerfile: Dockerfile
    container_name: reservue_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - app_var:/var/www/html/var
    networks:
    - flores_reservue_network
    depends_on:
      - mysql
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}?serverVersion=8.0&charset=utf8mb4"
    ports:
      - "8000:80"
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        environment:
          PMA_HOST: mysql
          PMA_USER: flores_user_reservue
          PMA_PASSWORD: flores_password_reservue
        ports:
        - "8080:80"
        depends_on:
        - mysql
        networks:
        - flores_reservue_network

volumes:
 mysql_data:

networks:
 flores_reservue_network:

